- hosts: all
  connection: local
  become: yes
  become_user: root
  gather_facts: no
  vars:
    docker_version: 5:18.09.0~3-0~ubuntu-bionic
    docker_compose_version: 1.24.1
    docker_compose_arch: Linux-x86_64

  tasks:

  - name: Add Docker's official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker's official repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Docker Install
    apt:
      name: docker-ce
      state: present
      update_cache: true

  - name: Docker CLI Install
    apt:
      name: docker-ce-cli
      state: present
      update_cache: true

  - name: containerd.io Install
    apt:
      name: containerd.io
      state: present
      update_cache: true

  - name: Ensure group "docker" exists
    group:
      name: docker
      system: yes
      state: present

  - name: Install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ docker_compose_arch}}
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: Install Python Requirements
    pip:
      name: ['docker', 'docker-compose']
      state: present

  - name: Add user vagrant to group docker
    user:
      name: vagrant
      state: present
      groups: docker
      append: yes
